web:
  build: .
  links:
    - mysql
    - redis
  environment:
   - BASE_URL=http://192.168.59.103:8083
  volumes:
      - ./src:/var/www/sentry/src
  ports:
    - "8083:80"

mysql:
  image: mysql:5.6
  environment:
   - MYSQL_DATABASE=postgres
   - MYSQL_USER=postgres
   - MYSQL_PASSWORD=123
   - MYSQL_ROOT_PASSWORD=123

redis:
  image: redis:latest
